version: '3.8'
services:
    server:
        build: ./server
        ports:
            - "8080:8080"
        volumes:
            - .server:/app
        restart: always
        depends_on:
            - db

    client:
        build: ./client
        ports:
            - "9090:9090"
        volumes:
            - ./client:/app
        restart: always
        depends_on:
            - server

    db:
        image: mysql:5.7
        environment:
            MUSQL_ROOT_PASSWORD: "root"
        ports:
            - "3306:3306"
